### ISSUE TITLE
[Recife] Oportunidade CLT com JavaScript Full Stack: back-end e aplicativos móveis

### ISSUE THREAD

**Issue by arthurpadilha** [devfsa/vagas#11]
**Oportunidade CLT com JavaScript Full Stack: back-end e aplicativos móveis**

A Artics é uma empresa de desenvolvimento de aplicativos criada em 2012 por ex-alunos do Centro de Informática da UFPE. A empresa conta com aplicativos na área de Educação de abrangência nacional: OAB de Bolso e Concursos de Bolso. Lançados em 2013, hoje os aplicativos já somam mais de 1,5 milhão de downloads. Nossa missão é inovar e personalizar a maneira como as pessoas aprendem.

Excelente oportunidade de aprendizado e de trabalhar com tecnologias recentes e de rápido crescimento como Node.js, Docker e Elasticsearch.

**Requisitos Mínimos:**

- Saber JavaScript
- Gostar de JavaScript

**Requisitos Desejáveis:**

- Experiência com JavaScript ES6 (Promises, etc)
- Node.js
- Titanium ou React Native
- Experiência com testes automatizados

**Perfil que buscamos:**

- Bastante motivação para aprender e contribuir
- Facilidade em aprender rápido
- Espírito de equipe
- Gostar de programar (projetos pessoais, contribuições open-source, etc)
- Buscar se manter sempre atualizado

**Sobre a Artics:**

- Startup de rápido crescimento
- Apaixonados por Educação
- Foco em Data Science e Machine Learning
- Cultura colaborativa

**Local de trabalho:**

- Ambiente descontraído
- Equipe bastante motivada e divertida
- Horário flexível
- Trabalho presencial
- Oportunidade de crescimento
- Café e lanches à vontade
- Comentar sobre seriados nas horas vagas
- Escritório em Boa Viagem próximo ao Shopping Recife, Recife-PE

Envie o Currículo para jobs@artics.com.br com o assunto "Oportunidade JavaScript - CLT".

**Comment by jonataa** [comment]
Oi, essa vaga ainda está disponível?

**Comment by arthurpadilha** [comment]
Olá.

Agradecemos o interesse em fazer parte da nossa equipe.

A vaga já foi preenchida, mas, se desejar, pode enviar o currículo e Github
para jobs@artics.com.br que consideraremos em avaliações futuras.

Abraços.
Arthur Padilha

Em sex, 19 de out de 2018 às 11:59, Jonata Weber <notifications@github.com>
escreveu:

**Comment by jonataa** [comment]
Obrigado, @arthurpadilha ! Então vou fechar a issue. Você pode reabri-la quando tiver disponível novamente.
