### ISSUE TITLE
[Feira de Santana] Back-End Developer no Gerenciagram

### ISSUE THREAD

**Issue by eng-assys** [devfsa/vagas#13]
![vaga empreggo1](https://user-images.githubusercontent.com/7086930/38943842-caed3348-4308-11e8-9c5f-81d174400885.png)

## Descrição da vaga

Back-end Developer para trabalhar no maior projeto de automação de Instagram do Brasil, o Gerenciagram

## Local

Escritório em Feira de Santana - Caseb

## Benefícios

- A combinar com o contratante

**Diferenciais:**

- 2 horas de almoço
- Horários flexíveis
- Campeonato de video-game
- Futebol com a galera da empresa

## Requisitos

**Obrigatórios:**
- Python3
- PostgreSql
- Django/Flask

**Desejáveis:**
- GIT

**Diferenciais:**
- Celery
- RabbitMQ
- APISTAR

## Contratação

- A combinar

## Nossa empresa

O Gerenciagram é mais que um sistema de automação, mas uma plataforma de gerenciamento para Instagram completa. Novas funções foram implantadas para facilitar a vida dos clientes e se tornaram um dos nossos diferenciais. Além disso, a preocupação com os usuários sempre foi algo presente na história da empresa, pois sempre investimos muito em uma equipe de atendimento qualificada, uma central de call center e um time de desenvolvimento incrível. Todo esse empenho já gerou frutos, pois conquistamos o prêmio de melhor ferramenta de Marketing Digital de 2017.

## Como se candidatar

Por favor envie um email para rh@gerenciagram.com.br com seu CV anexado - enviar no assunto: Vaga de Front-End Developer

**Comment by jonataa** [comment]
Oi, essa vaga ainda está disponível?

**Comment by eng-assys** [comment]
OPa, não mais. Vou fechar a issue
