### ISSUE TITLE
[Remoto ou alocado em Club4Work] Developer PHP e ou Nodejs

### ISSUE THREAD

**Issue by caburasdev** [devfsa/vagas#14]
## Descrição da vaga

Vaga para developer web

Conhecimento avançado em PHP e Frameworks: Cakephp 3.X e Zend
Conhecimento em Nodejs
Conhecimento em JSONRPC, Web3 ,Websockets, Web3.eth

Banco de dados e similares Mysql/Mariadb, MongoDB, Firebase

Conhecimentos em Reactjs e Vuejs ganha pontos extras

## Local

Alocado em Feira de Santana na Club4Work
Ou
Home Office

## Benefícios

Extra por produdução
ExtraX2 por sinistro (Noite virada ou chamadas de emergência)

## Requisitos

**Obrigatórios:**
- Responsabilidade
- Sigilo total sobre o projeto
- Ter conhecimento avançado nos requisitos citados

## Contratação

PJ/Contrato

## Nossa empresa

Vaivo Panama
(contrato será firmado com empresa de suporte no Brasil)

## Como se candidatar

Nada de enviar CV e formação acadêmica é irrelevante.

Contato pelo email jordan@vaivo.com descrevendo o nível de conhecimento em cada linguagem citada, mencionar conhecimentos adicionais caso tenha, citar dois projetos em quais trabalho e quais foram demandas, desafios e como somou ao projeto.

Github ou envio de projeto via bitbucket para jordan@vaivo.com para primeira avaliação.

Informação adicional, após a primeira etapa da avaliação eu vou sugerir um desafio envolvendo o requisitos acima, será avaliado, tempo de desenvolvimento, qualidade do código e sugestões de melhoria.

A avaliação será remunerada por hora de desenvolvimento, valor fixado nas horas limites para conclusão do desafio.

**Comment by fsrocha-dev** [comment]
Ainda em aberto esta vaga ?
