### ISSUE TITLE
 Front-End Developer na Achei Interativa

### ISSUE THREAD

**Issue by fabriciooliveira21** [devfsa/vagas#15]
Olá pessoal, surgiu uma nova oportunidade para Front-End Developer no time de TI da Achei Interativa.

Um pouco sobre nós: Nascemos da PAIXÃO desenvolvida pelas REDES SOCIAIS, sua capacidade de aproximação ao público de forma íntima, completa e EFICIENTE.

Requisitos:
- Conhecimento nas linguagens básicas de front-end (HTML/CSS/JS);
- Domínio em photoshop, illustrator e outras similares;
- Possibilidade de trabalho remoto (não presencial);
- Desejável: Conhecimento em social media marketing;

Salário a combinar. 
Enviar currículo para fabricio@acheiinterativa.com.br com seu CV anexado - enviar no assunto: Vaga Front-End Developer

**Comment by crisgon** [comment]
Olá, essa vaga ainda está aberta?

**Comment by fabriciooliveira21** [comment]
Está sim.

**Comment by pereiraigorbr** [comment]
@fabriciooliveira21 a vaga continua aberta?

**Comment by jonataa** [comment]
Oi, essa vaga ainda está disponível? @fabriciooliveira21

**Comment by jonataa** [comment]
@fabriciooliveira21 vou fechar a issue. Você poderá reabri-la caso a vaga ainda esteja disponível.
