### ISSUE TITLE
[Feira de Santana] Front-End Developer na Slim

### ISSUE THREAD

**Issue by dyegoteles** [devfsa/vagas#18]
## Descrição da vaga

Nossa equipe está à procura de um desenvolvedor Front-End. Você se encaixa nos requisitos? Então, esta é a sua oportunidade!

## Local

Feira de Santana, Bahia

## Requisitos

**Obrigatórios:**
- HTML5
- CSS3
- Bootstrap 4
- JavaScript
- jQuery
- CMS **( Wordpress )**

**Desejáveis:**
- Conhecimento sólido em algum framework JS **( Ember, Angular, React ou BackboneJS, etc.)**
- Conhecimento sólido em sistema de versionamento de código **( Git )**
- Conhecimento sólido em programação **( PHP, Python )** e frameworks **( Laravel ou Django )**

## Contratação

PJ a combinar

## Nossa empresa

A **Slim** é uma Agência de Marketing Digital com 9 anos de atuação e mais de 200 clientes atendidos. Nós ajudamos empresas a conquistarem mais resultados através da internet.

Acreditamos que a forma de se comunicar mudou. A internet é o maior meio de comunicação do mundo. Nesse contexto, a nossa missão é conectar empresas e pessoas por meio do digital.

Nosso sucesso depende do sucesso do nosso cliente, por isso estamos comprometidos com o resultado. 

## Como se candidatar

Para participar da seleção, basta se inscrever nesse link: https://goo.gl/forms/SXx1ARtJlPFSs91w2

**Comment by jonataa** [comment]
Oi, essa vaga ainda está disponível?

**Comment by jonataa** [comment]
@dyegoteles, vou fechar a issue. Você pode reabri-la caso a vaga ainda esteja disponível.

**Comment by dyegoteles** [comment]
ok
*___*

*Dyego Teles - Interactive Designer*
Telefone: (71) 99146.3745
Email: contato@dyegoteles.com  (Hangouts)

Twitter <https://twitter.com/#!/dyegoteles> | LinkedIn
<http://br.linkedin.com/in/dyegoteles> | Portfólio
<https://www.behance.net/dyegoteles>


Em ter, 23 de out de 2018 às 07:24, Jonata Weber <notifications@github.com>
escreveu:
