### ISSUE TITLE
[Feira de Santana] Programador PHP Pleno na Lince Web

### ISSUE THREAD

**Issue by linceweb** [devfsa/vagas#2]
## Descrição da vaga

Análise e desenvolvimento de aplicações Web. Manutenção em plataforma. Implantação e realização de manutenção de sistemas e aplicações. Utilização de metodologias ágeis. Realização de testes unitários dos desenvolvimentos realizados. Desenvolvimento de aplicações PHP, MySQL, jQuery e Vue.

## Local

Avenida Getúlio Vargas, 2596 - Parque Getúlio Vargas.

## Benefícios

- Horário flexível (8 horas entre as 08:00 e 20:00)
- Oportunidade de crescimento num ambiente em constante mudança
- Sistema de reconhecimento por meritocracia e pontuação
- Ambiente descontraído
- Cafezinho a vontade
- Auxílio alimentação
- Auxílio transporte

## Requisitos

**Obrigatórios:**
- Ser responsável, organizado, comunicativo e amar o que faz
- Experiência com Frameworks
- Gostar de trabalhar em equipe
- Gostar de estudar e aprender sempre
- Conhecimento em HTML (semântica e micro-data), CSS3 (animações e performance) e  Javascript.
- Trabalhar em conjunto com um time multidisciplinar (Design, Conteúdo, Back-end, e outros)

**Desejáveis:**
- Experiência com o framework Laravel
- Ter trabalho com práticas Agile (Scrum, Kanban, XP)
- Inglês

## Contratação

A combinar

## Nossa empresa

Consolidada no mercado há de mais de 8 anos, adquirimos uma expertise que nos permite ir muito além de analisar cliques. Nos comprometemos com o negócio dos nossos clientes a fim de entregar resultados relevantes e superar as expectativas.
A cada projeto inicia-se um novo desafio. Com nosso Know-how formulamos os objetivos com muita garra, levando em consideração as condições internas e externas à empresa e a evolução esperada. Isso nos permite alcançar metas com precisão e objetividade.
Com nosso caráter singular e visão estratégica, acompanhamos de forma analítica e minuciosa todos o projeto, objetivos e resultados. Dados, números e métricas, nos familiarizamos com essas palavras para monitorar todos os passos dos visitantes no seu site e projetar novas estratégias além de otimizar a experiência do seu cliente.

**Metodologia:**
Entender, Planejar, Desenvolver e Acompanhar os resultados, garantindo a satisfação do cliente com soluções criativas, ideias inovadoras e serviços de qualidade que superem suas expectativas.

## Como se candidatar

Por favor envie um email para rh@linceweb.com.br fazendo sua apresentação e histórico profissional.
- Descreva a sua equipe atual (ou anterior, se não estiver empregado no momento). O que você gosta e não gosta?
- Qual foi seu maior fracasso até o momento?
- Nos conte sobre o momento em que você mais trabalhou em sua vida. Fique à vontade para contar experiências profissionais, pessoais e na vida acadêmica.
- Como você descreve a sua personalidade?

**Comment by raloliver** [comment]
é impressão minha ou usaram nosso modelo como exemplo: https://github.com/devfsa/vagas/issues/1 ? 🤔

**Comment by linceweb** [comment]
Usamos sim.
E na postagem da vaga vem esse modelo.

Algum problema?


Em 19 de jan de 2018 9:36 AM, "Israel Oliveira" <notifications@github.com>
escreveu:

**Comment by ssscassio** [comment]
@raloliver Esse é o template das issues do repositório. Ta assim para padronizar todas as submissões de vagas. 👍

**Comment by raloliver** [comment]
@linceweb 👍

**Comment by ssscassio** [comment]
Olá @linceweb ,  essa vaga continua aberta?
Para saber se a issue continua aberta.

[Informação Importante](https://github.com/devfsa/vagas#importante)

**Comment by linceweb** [comment]
Estamos fazendo uma experiência com um candidato. Mas ainda não contratamos.

Podemos combinar nesta segunda, na Lince, as 14h, uma rápida entrevista.

Ok?

Me mande um email:
marcos@linceweb.com.br

Abraços.

**Comment by jonataa** [comment]
Oi, essa vaga continua aberta?

**Comment by jonataa** [comment]
@linceweb vou fechar a issue. Você poderá reabri-la caso a vaga ainda esteja disponível.
