### ISSUE TITLE
[Estágio] Back-End Developer na SLIM

### ISSUE THREAD

**Issue by dyegoteles** [devfsa/vagas#20]
## Descrição da vaga

Estamos com vaga aberta para Desenvolvedor Back-End! Quer trabalhar na Slim? Presta atenção:⠀

## Local

Feira de Santana

## Requisitos

**Obrigatórios:**
- HTML
- CSS
- PHP
- MySQL

**Desejáveis:**
- Conhecimento em algum sistema de versionamento de código **(Git)**
- Conhecimento em Framework **(Laravel)**

## Nossa empresa

A **Slim** é uma Agência de Marketing Digital com 9 anos de atuação e mais de 200 clientes atendidos. Nós ajudamos empresas a conquistarem mais resultados através da internet.

Acreditamos que a forma de se comunicar mudou. A internet é o maior meio de comunicação do mundo. Nesse contexto, a nossa missão é conectar empresas e pessoas por meio do digital.

Nosso sucesso depende do sucesso do nosso cliente, por isso estamos comprometidos com o resultado.

## Como se candidatar

Para participar da seleção, basta acessar esse link: https://linktr.ee/agenciaslim

**Comment by jonataa** [comment]
Oi, essa vaga ainda está disponível?

**Comment by jonataa** [comment]
@dyegoteles vou fechar a issue. Você pode reabri-la caso a vaga ainda esteja disponível.
