### ISSUE TITLE
[São Paulo] [Realocação] Software Engineer at QuintoAndar

### ISSUE THREAD

**Issue by cleristonos** [devfsa/vagas#22]
## DESCRIPTION

**QuintoAndar** is a technology company that enables a seamless rental experience from discovery to closing. Through the intensive use of technology and design, we are redesigning the entire rental process, from one end to the other, to allow the kind of customer experience that we wish for ourselves. As a result, we are creating a new business model that is unique in the whole world and that will revolutionize the real estate industry.

Technology and design are core components of our DNA. Our team works very very hard, with cutting edge technology and design practices, to invent web and mobile tools that are first of their kinds in the whole world.

**At QuintoAndar you will:**

- Work with a top-notch team that uses the best practices and best tools.
- Learn a lot.
- Be part of a high-impact project that will affect many people's lives.
- Have autonomy to make decisions with no endless meetings or bikeshedding.
- Work in an informal environment and horizontal hierarchy.

**Developer responsibilities at QuintoAndar**
- Help develop independent (micro-)services that address specific solutions (e.g. parts of billing, visit scheduling, price optimization, self-service negotiation);
- Create easy-to-understand, well-documented APIs.
- Fix or upgrade existing solutions or services. Most of them are in Python over SQL databases, but we also happen to carry significant Java, NodeJS, Clojure, Cloudsearch, Datomic. You don't need to know all these upfront, but you need to learn fast.
- Code really good software.

**Language and location**

We are a Portuguese speaking company. This is written in English because 1) we value diversity and thus welcome foreign candidates, and 2) if you are Brazilian you need to be fluent in English in order to learn the most from the rest of the world.

Our office is in Sao Paulo, at Av Paulista, near 'metrô Consolação'.

**About our selection process:**

It usually takes around 20 days (from your applying to the end) and follows this steps:

1. Application Screening
2. Technical Online Challenge
3. Phone interview with Recruiters
4. Interview with Engineering Team
5. Reference check
6. Offer

**Important:** Our recruitment process starts at the application form! If you really wish be a part of our team, endeavor to do well at this stage of the process. We analyze all the candidates individually. Yes, we do read all applications and we’ll reply even to those who won't follow the process.

##  REQUIREMENTS
**You may apply if you:**
- Have an academic degree in computer science/engineering (or equivalent).
- Are used Java or Python, and relational databases.
- Also like other programming languages (Clojure, NodeJS, Datomic etc) and you don't mind learning new ones on the fly.
- Have very strong analytic skills.
- Are fluent in English and Portuguese.

**We might like you even better if you:**
- Have strong knowledge of computer theory, including optimization of algorithms and distributed systems.
- Have some experience using RESTful APIs.
- Have some experience with AWS or Google Cloud services;
- Have some knowledge in Docker, modern CDs/CIs (Jenkins, Travis, Circle, Drone, ...);
- Know how to test and tune scalability.

## BENEFITS
**Working here is cool AND you get the following:**

- Competitive salary package.
- Meal allowance ("ticket refeição and/or ticket alimentação").
- Fuel or public transportation allowance.
- Good health plan
- Dental plan
- Life insurance
- Children Allowance (Daycare)
- Subsidy to sports practicing (Gympass)
- **This position offers relocation package for people who would have to move to Sao Paulo**
- Free beer every Friday
- Very fun, collaborative, and fast-paced work environment - full of smart and ambitious people (know more in this video)

## Apply for this job

https://quintoandar.workable.com/j/1BD0A37B4D

**Comment by jonataa** [comment]
A vaga ainda está disponível?
Se não tiver, encerre a issue, por favor ;)

**Comment by cleristonos** [comment]
Fechando pq a descrição está desatualizada. Em breve publico as novas posições.
