### ISSUE TITLE
[Feira de Santana]Front-End Developer na Próton Sistemas

### ISSUE THREAD

**Issue by dhielyton** [devfsa/vagas#29]
## Descrição da vaga

Responsável em desenvolver camada cliente da aplicação consumindo Api Restfull, utilizando conceitos de interface  UX/UI Designer.

## Local

Escritório Feira de Santana

## Benefícios

- Plano de saúde

## Requisitos

**Obrigatórios:**

- Html, CSS, Javascript
- Bootstrap, Jquery
- Angular ( a partir da versão 2.x)
- TDD utilizando preferencialmente Jasmine, porém pode ser utilizando outro Framework.

**Desejáveis:**

- Design Patterns
- Conhecimentos em SOLID
- Conhecimentos em C#
- Conhecimento na Metodologia Scrum

- Versionamento com GIT
- Conhecimentos UX/UI Designer

## Contratação

CLT, Salário de 2500 + Vale Transporte

## Nossa empresa

A PRÓTON é uma empresa brasileira que opera desde o ano de 2003 produzindo softwares, como o ERP, o WMS e o PMS e prestando consultorias de processos e de logística. Os mercados de atuação são a indústria, o atacado/distribuidor, o varejo e o serviço. Temos especialistas que conhecem profundamente as características desses mercados, o que nos faz melhores no que fazemos. Nossa meta é estar aliados a players importantes no mercado para que os nossos clientes tenham melhores resultados. Com base em alianças estratégicas como as que já temos com a TW2 e a SOPORTEC (Costa Rica), estamos ampliando nosso horizonte de atuação e de conhecimento, trazendo mais soluções para o nosso mercado de atuação.

A empresa é composta por três sócios atuantes e mais de 30 colaboradores diretos, e atua com uma rede de Revendas em expansão.

## Como se candidatar

Mandar e-mail para dhielyton.araujo@protonsistemas.com.br com assunto "FRONT-END DEVELOPER" e o CV anexado.

**Comment by nunesbeto** [comment]
curti!

--
Att.,
Beto Nunes


Em sex, 25 de jan de 2019 às 12:02, dhielyton <notifications@github.com>
escreveu:

**Comment by dhielyton** [comment]
Alocado
