### ISSUE TITLE
[SALVADOR] Arquitetura de Software na Solutis

### ISSUE THREAD

**Issue by ticianafig** [devfsa/vagas#34]
A Solutis está em busca de profissionais que sejam criativos e proativos, aficionados por desenvolvimento ágil e em constante busca por novos conhecimentos para integrar o seu time de aplicações!

## Descrição da vaga

O Arquiteto(a) de Software é peça central no desenvolvimento das aplicações – web e mobile – da Solutis. Para encarar esse desafio é necessária ampla experiência e sede de conhecimento para definir padrões de projeto e uso de tecnologias a serem implementadas, visando a otimização e economia de recursos.

São responsabilidades do Arquiteto(a) de Software:

- Analisar e elaborar arquitetura de software para sistemas web e mobile
- Documentar arquiteturas propostas
- Avaliar novas arquiteturas e tecnologias para futuros projetos
- Realizar revisões de código para garantir artefatos padronizados e de qualidade
- Orientar implementações de testes automatizados
- Propor modelos de desenvolvimento que aumente a qualidade dos produtos e a agilidade dos times

## Local

Salvador - BA

## Benefícios

- Salário compatível com o mercado
- Horário flexível
- Auxilio deslocamento e instalação possível!

## Requisitos

- Experiência com arquiteturas de aplicações monolíticas, microserviços, reativas, síncronas, assíncronas
- Experiência com banco de dados relacionais (MSSQL ou MySql ou PostgreSQL ou Oracle)
- Experiência com banco de dados NoSql (MongoDB ou Redis)
- Experiência com ambientes CI (Jenkins ou GitLabCI)
- Experiência com webservices (REST, SOAP)
- Experiência com tecnologias como: Java, Angular, Javascript, Node.js, JBoss, JPA, EJB, CDI, JAX-RS, C#, Git, SVN, SSL, Apache Kafka, RabbitMQ, ActiveMQ, GrayLog

**Diferenciais:**
- Conhecimento em arquiteturas moveis (MVVM, MVP, VIPER)
- Conhecimento/experiência em desenvolvimento mobile com Kotlin, Swift ou React.

## Nossa empresa

Somos apaixonados por gente e esse valor está presente em nossas ações e proposta de trabalho. Ambiente descontraído e criativo, horário flexível, possibilidade de trabalho home office, eventos e programas internos com games... Isso faz parte do nosso dia-a-dia.

Engajamento, busca intensa por conhecimento, empatia e criatividade são a nossa receita para cultivar e colher, sempre, o melhor resultado tecnológico.

Essa é a Solutis, flexível, acolhedora, inquieta, amante da tecnologia e de tudo que ela nos proporciona de mais incrível.

Venha fazer parte do nosso time!

## Como se candidatar

Inscreva-se em: https://vagas.byintera.com/solutis/arquiteto-de-software/

**Comment by jonataa** [comment]
A vaga ainda está disponível?
Se não tiver, encerre a issue, por favor ;)
Obrigado!
