### ISSUE TITLE
[Feira de Santana] Full Stack Developer at CEAF

### ISSUE THREAD

**Issue by Otooo** [devfsa/vagas#36]
## Descrição da vaga

Vaga para Full-Stack Developer na prefeitura de feira de santana. Trabalho envolvendo a manipulação com alguns tributos municipais (exemplo de IPTU, ISS e ITIV).

## Local

CEAF, Feira de Santana - Getúlio Vargas

## Requisitos

**Desejáveis:**
- conhecimentos em laravel
- conhecimentos em php
- conhecimentos em oracle
- conhecimentos em mysql

## Contratação

CLT - 40 horas/s

## Como se candidatar

Por favor envie um email para oto@sefaz.feiradesantana.ba.gov.br com seu CV anexado - enviar no assunto: Vaga CEAF

**Comment by nunesbeto** [comment]
40 horas?

--
Att.,
Beto Nunes


Em ter, 12 de mar de 2019 às 09:21, Oto <notifications@github.com> escreveu:

**Comment by Otooo** [comment]
Sim
