### ISSUE TITLE
[Feira de Santana e Região] Back-End Developer na Huggy

### ISSUE THREAD

**Issue by raloliver** [devfsa/vagas#4]
## Descrição da vaga

O developer backend poderá trabalhar na área de produto ou tecnologia na Huggy. Tendo como principais atividades: desenvolvimento de novas features solicidatas pelos stakeholders, pesquisa e modelagem de novas soluções que otimizem performance e escalabilidade do sistema, integrações com sistemas e APIs de parceiros.

## Local

Feira de Santana - BA no Club4Work Coworking

## Benefícios

- Horário flexível (8 horas entre as 08:00 e 20:00)
- Oportunidade de crescimento num ambiente em constante mudança
- Ambiente diferenciado (Você vai curtir!)
- Bolsa 50% em Curso de Inglês

#### Diferenciais

- Pode trabalhar de bermuda e crocs
- Cafezinho livre
- Lanches livre
- Frutinhas sempre frescas
- Jogatina garantida no final da tarde
- NerfTime (venha preparado pra batalha)

## Requisitos

**Obrigatórios:**

- Conhecimento em PHP (7.x), Node.js, APIs, Aurora (ou MySQL-like).
- Alguma vivência com tecnologias frontend (Webpack, React etc.)
- Alguma experiência de montagem de páginas de HTML, CSS e JS (frontend)
- Grande vivência em tecnologias e ferramentas voltadas ao backend
- Ser criativo, organizado, comunicativo e amar o que faz
- Desenvolver com boas práticas de segurança, performance, padronização e escalabilidade
- Alguma vivência com ambiente Linux
- Gostar de trabalhar em equipe
- Gostar de estudar e aprender sempre
- Trabalhar em conjunto com um time multidisciplinar (Design, Conteúdo, Frontend, e outros)

**Desejáveis:**

- Boa noção de Inglês
- Ter trabalho com práticas Agile (Scrum, Kanban, Lean, XP)
- Background em cloud computing (AWS)
- Noções de boas práticas de evolução e manutenção de software
- Noções de testes de software
- Noções de algum pré-processador CSS (SASS, LESS, Stylus, Compass etc.)

**Diferenciais:**

- Inglês avançado
- Ter criado APIs para serviços RESTful
- Experiência com bancos de dados relacionais e NoSQL
- Contribuição em projetos opensource
- Participação e colaboração em comunidades

## Contratação

A combinar

## Nossa empresa

Olá! Tudo bem?

Gostaríamos de nos apresentar. Somos uma solução que integra os mais diversos canais de comunicação de sua empresa a fim de tornar o relacionamento entre sua marca e seus clientes mais eficiente e prazeroso.

Mas por que isso é importante?

Essa é uma ótima pergunta! A diversidade de ferramentas de comunicação pode contrariar a continuidade no atendimento aos clientes e, ao mesmo tempo, impossibilitar um controle integrado das estratégias de comunicação. É por isso que acreditamos que a comunicação deve ser mais inteligente, humana e envolvente.

E é aí que a gente entra!

Nós utilizamos o que há de mais inovador em tecnologias cognitivas para tornar o atendimento a cada um de seus clientes sempre eficiente e personalizado, seja qual o meio de contato por ele escolhido. Nós, da Huggy, sabemos que as tecnologias, quando bem aplicadas, podem potencializar 
 excepcionalmente a proximidade, a naturalidade e a eficiência dos meios por onde pessoas se relacionam.

E então, vamos conversar melhor?

## Como se candidatar

Por favor [acesse este link](http://bit.ly/huggy-applications2) e preencha os campos com seu CV, github, linkedin e o que mais achar interessante. E responda por email as seguintes perguntas para calebe.oliveira@huggy.io, com o assunto Vaga Backend.

1. Descreva a sua equipe atual (ou anterior, se não estiver empregado no momento). O que você gosta e não gosta?
1. Qual foi seu maior fracasso até o momento?
1. Nos conte sobre o momento em que você mais trabalhou em sua vida. Fique à vontade para contar experiências profissionais, pessoais e na vida acadêmica.
1. Como você descreve a sua personalidade?

**Comment by ssscassio** [comment]
Opa @raloliver . Poderia dizer qual das labels gostaria que fossem adicionadas? 
[https://github.com/devfsa/vagas/labels](https://github.com/devfsa/vagas/labels)

**Comment by raloliver** [comment]
Alocado e Sênior

**Comment by jonataa** [comment]
Oi, essa vaga continua aberta?

**Comment by uamartins** [comment]
@jonataa não, pode fechar também, vlw.

**Comment by jonataa** [comment]
Valeu, @uamartins ! Qualquer novidade pode reabrir.
