### ISSUE TITLE
Front-End Developer Junior/Intermediário

### ISSUE THREAD

**Issue by jmo-jr** [devfsa/vagas#46]
Bom em JS, de preferência utilizando Vue ou outro framework JS

Presencial, 40h semanais.

## Como se candidatar

Por favor, envie seu CV para italo.ecomp@gmail.com com proposta salarial.

**Comment by abelsouzacosta** [comment]
A vaga ainda está aberta?
Tenho interesse mas ainda não possuo o domínio de nenhum framework

**Comment by jonataa** [comment]
@jmo-jr A vaga ainda está aberta? Como o @cyberdeadd não teve resposta, presumo que esteja encerrada. Vou fechar a issue, mas você pode reabrir se quiser.

**Comment by jmo-jr** [comment]
Perdão amigo. Não atentei para isso. A vaga já foi preenchida há tempos. Desculpe @cyberdeadd por não te dar uma resposta no tempo certo.
