### ISSUE TITLE
[Feira de Santana] Full-Stack Developer na Conexa

### ISSUE THREAD

**Issue by biabsantana** [devfsa/vagas#50]
## Descrição da vaga

A Conexa, uma das maiores startups feirenses, está com processo de seleção aberto para vários cargos, inclusive para Full-Stack Developer!  

## Nosso santo vai bater se você…  🙏
- For focado em resultados;
- É proativo;
- Se identifica com ambiente de startup;
- É motivado por desafios;
- É apaixonado por desenvolvimento de software;
- Escreve um código limpo para leitura e manutenção;
- Gosta de aprender coisas novas;
- For bem humorado.

## Seria legal se você tivesse… 👍
- Experiência com framewoks PHP;
- Experiência com HTML, CSS e JavaScript;
- Experiência com banco de dados relacional;
- Conhecimento básico em Git.

## O que você vai ter aqui com a gente:  😍
- Modelo de Contratação CLT;
- Vale alimentação;
- Horário flexível;
- Ambiente altamente colaborativo, inovador e desafiador;
- Cultura de startup: descontraído, descolado e preocupado com seu bem-estar na empresa;
- Participação em um time de alto nível!

## Local

Feira de Santana - Capuchinhos

## Nossa empresa
Aqui na Conexa temos um propósito desafiador: ajudar gestores de coworkings de todo Brasil a administrar melhor suas finanças, espaços e membros. Para isso, usamos muita tecnologia e a maior delas é a tecnologia humana. 
Com um desafio desse tamanho não temos a menor dúvida que o mais importante é sermos um time de pessoas incríveis. Precisamos de pessoas talentosas, apaixonadas pelo que fazem e que querem ir cada vez mais longe. Se você se encaixa nesse perfil, temos uma vaga para você!

## Como se candidatar

 Faça sua inscrição em nosso site https://conexa.app/jobs

**Comment by romualdoandre** [comment]
Já preencheu a vaga?

**Comment by biabsantana** [comment]
As vagas foram preenchidas.
