### ISSUE TITLE
[Feira de Santana] Cloud Expert / DevOps Engineer at AdMobilize

### ISSUE THREAD

**Issue by di3goleite** [devfsa/vagas#52]
## Job Description

We're looking for a very passionate developer, with high level skills in DevOps Engineering. If you like challenges and have a willingness to learn and share knowledge this job is for you. Those are the main responsibilities:

- Lead Google Cloud Platform based architecture and deployment strategies for a wide variety of micro services and applications.
- Continuously leverage modern application development tools and frameworks and identify key strategies for cost effective application deployment.
- Continuously identify and implement key strategies for containerized application deployment on top of Kubernetes. 
- Lead and implement service mesh strategies that improve service reliability and security across the service ecosystem. 
- Automate and maintain application deployments .

## Location

Feira de Santana - Bahia

## Benefits

- Flexible Schedule
- Growing company, you'll grow with us.
- Payment set in dollars

## Requirements

- **5-7 years of experience** deploying applications on Amazon Web Services / Google Cloud Platform. 
- **2-4 years minimum** experience working with Docker containers and Kubernetes.
- **2-4 years minimum** experience working with CI systems such as Drone CI, Circle CI, Travis CI, Spinnaker.
- Experience working with gRPC a plus.
- Experience with Google IoT core is a plus.
- Working knowledge in Agile methodology.
- Strong leadership, communication and collaboration skills.
- Professional level English knowledge.

## Our company

We're global team of 40 determined to give everyone in the world access to building technology-driven solutions for challenges they and others face. We speak over 10 languages and we're revolutionising the way Out-Of-Home Advertising works through of digitalising the physical world and bringing to advertisers analytical data so they can take better decision and have the best return of investment.

## How to apply

Please send a email with you resume to careers@admobilize.com with the subject: Cloud Expert / DevOps Engineer

**Comment by jonataa** [comment]
A vaga ainda está disponível?
Se não tiver, encerre a issue, por favor ;)
Obrigado!

**Comment by di3goleite** [comment]
Não me recordava que essa issue ainda estava aberta. Obrigado por lembrar e me notificar. Vou encerrar aqui. 👍
