### ISSUE TITLE
[Feira de Santana] Back-End Developer na [AGÊNCIA SLIM]

### ISSUE THREAD

**Issue by slimgithub** [devfsa/vagas#53]
## Descrição da vaga

Faça parte do time Slim!
Estamos com vaga para Desenvolvedor Back-End!
Estágio e Júnior (os requisitos obrigatórios, tornam-se desejáveis no caso de estágio)

## Local

Escritório, Feira de Santana - Ponto Central

## Requisitos

**Obrigatórios:**
• Experiencia com migrações de bancos de dados MySQL e MongoDB
• Laravel
• Vue.js

**Desejáveis:**
• nodeJS para acesso a APIs
• Experiência em adaptação de código legado em MVC
• Experiência de integração de end-points  
• Sistema de versionamento de código (Git)

## Contratação

A combinar

## Nossa empresa

A Slim é uma Agência de Marketing Digital com 11 anos de atuação e mais de 300 clientes atendidos. Nós ajudamos empresas a conquistarem mais resultados através da internet.
Nosso sucesso depende do sucesso do nosso cliente, por isso estamos comprometidos com o resultado.

## Como se candidatar

Você se encaixa no perfil? Envie seu currículo ou portfólio para vagas@agenciaslim.com.br
Não se encaixa, mas conhece alguém que sim? Menciona a pessoa nos comentários. Boa sorte!

**Comment by jonataa** [comment]
A vaga ainda está disponível?
Se não tiver, encerre a issue, por favor ;)
Obrigado!

**Comment by slimgithub** [comment]
vaga preenchida.
