### ISSUE TITLE
[Salvador] Front-End Developer (DD Corporation)

### ISSUE THREAD

**Issue by franciscobrba** [devfsa/vagas#54]
## Descrição da vaga

Pense grande, somos um grupo evangelizador de tendências de mercado, promovendo a acessibilidade do conhecimento sobre o mercado de criptomoedas. Parceiros são treinados e capacitados para se tornarem especialistas neste mercado que cada vez mais cresce.

Precisamos de alguém com com experiência razoável para desenvolvimento de um sistema MMN.

## Local

Salvador, Av. Tancredo Neves

## Benefícios
- Nossa equipe sempre compartilha do progresso da empresa

**Diferenciais:**
- Horário flexível
- Escritório moderno

## Requisitos

**Obrigatórios:**
- Conhecimento sólido em Javascript/Node
- Conhecimento de algum framework/library moderna (Pref. Vue.js)
- Experiência com deploy de sistemas

**Diferenciais:**
- Experiência em empresas grandes

## Contratação

PJ

## Como se candidatar

Basta enviar um email para social@ddcorporation.com com seu CV anexado, ou LinkedIn

**Comment by nunesbeto** [comment]
Alguma chance de job remoto?

**Comment by franciscobrba** [comment]
> Alguma chance de job remoto?

por enquanto não!

**Comment by jonataa** [comment]
A vaga ainda está disponível?
Se não tiver, encerre a issue, por favor ;)
Obrigado!

**Comment by franciscobrba** [comment]
fechado!
