### ISSUE TITLE
[REMOTO] Mobile Developer Pleno/Senior na Skilopay

### ISSUE THREAD

**Issue by jonataa** [devfsa/vagas#58]
## Descrição da vaga

Que tal resolver problemas do mercado financeiro e impactar milhões de pessoas? A Skilopay é uma empresa de tecnologia que desenvolve produtos e serviços financeiros. Atualmente está em busca de profissionais para compor seu time de Banking para o desenvolvimento de um aplicativo.

## Local

100% Remoto (somos uma empresa remote first)

## Benefícios

- Salário competitivo;
- Participação nos lucros;

**Diferenciais:**

- Trabalhe de onde quiser;
- Horário flexível;
- Tecnologias de ponta;
- Ajuda de custo para montar seu home office;

## Requisitos

**Obrigatórios:**
- React Native

**Desejáveis:**
- TypeScript
- GraphQL/Apollo

## Contratação

CLT ou PJ

## Nossa empresa

Somos uma empresa recém criada, ainda em fase de lançamento, mas pretendemos crescer MUITO nos próximos meses. Queremos impactar milhões de pessoas!

## Como se candidatar

Por favor, envie um email para jonata@skilopay.com.br com seu currículo ou linkedin - enviar com assunto: Vaga Mobile Developer

**Comment by ribeiroevandro** [comment]
Email enviado

**Comment by eltonmarques96** [comment]
Currículo enviado
