### ISSUE TITLE
[Salvador] Desenvolvedores(as) full-stack PHP na Agilize Contabilidade Online

### ISSUE THREAD

**Issue by cleristonos** [devfsa/vagas#6]
![26239402_1839003099466311_4542790046644881070_n](https://user-images.githubusercontent.com/4993022/36795108-e752b322-1c80-11e8-8ca0-b266eb9ebf2c.png)

## Descrição da vaga

**Agilize** é o primeiro escritório de contabilidade on-line do Brasil. Somos uma startup baiana, com escritórios em Salvador e São Paulo, que atua em 20 cidades no Brasil. Trabalhamos diariamente para automatizar processos contábeis e fiscais, trazendo tranquilidade, regularidade e redução de custos para nossos clientes.

Procuramos desenvolvedores e desenvolvedoras full-stack experientes em **PHP** e **JavaScript** dispostos a tornar a contabilidade cada vez mais automatizada, sem abrir mão de um bom atendimento..

## O que esperamos de você

- Ter espírito ágil, que adapta-se às mudanças
- Abraçar desafios e questionar a inércia
- Orientar-se à resultados
- Fazer questão de entender o impacto do trabalho
- Construir coisas com excelência

## Habilidades que buscamos

- PHP moderno
- Boas práticas de OO, design patterns, refatoração e princípios de design (como SOLID);
- Construção de APIs RESTful
- Bancos de dados relacionais (MySQL, PostreSQL)
- Infraestrutura como código (Docker, Ansible etc.)
- JavaScript moderno --usamos Angular, mas estamos migrando para React; HTML, CSS
- Conhecer aplicações híbridas para smartphones

## Habilidades que somam pontos

- Testes automatizados (unitário, funcional, integração)
- Falar, escrever e compreender bem Inglês
- Ter experiência com BPMN

## O que você fará no dia a dia

- Evoluir aplicativos web e híbridos
- Construir interfaces de usuário para ajuda-los a completar suas atividades sem sofrimento;
- Construir e evoluir aplicações híbridas para dispositivos móveis;
- Vivenciar práticas ágeis (XP/Scrum) de maneira pragmática e evolutiva;
- Traduzir regras contábeis e fiscais em software;
- Salvar humanos de trabalho repetitivo;
- Modelar e automatizar processos contábeis e fiscais orquestrados via software;
- Automatizar até o limite da honra;
- Comunicar-se com softwares de terceiros, mesmo que não existam APIs :)
- Monitorar e melhorar a plataforma a performance das nossas APIs e UIs;
- Aprender sobre contabilidade e impostos :)
- E coisas novas que não sabemos, mas com as quais você se envolverá

## Benefícios

- Ambiente amigável que estimula produtividade, colaboração, crescimento e coragem;
- Localizado próximo à Av. Tancredo Neves, colado com o metrô e com o Salvador Shopping;
- 40 horais semanais, com flexibilidade;
- Time interdisciplinar;
- Vale transporte;
- Vale alimentação;
- Plano de saúde (cobrimos 60%);

## Local
Alameda Salvador, 1057, Caminho das Árvores, Salvador/BA

## Como se candidatar
Mande seu currículo para dev at agilize.com.br ou aplique pelo [indeed](https://www.indeedjobs.com/agilize-contabilidade-online/jobs/162f34a455df2d849924)

**Comment by jonataa** [comment]
Oi, essa vaga continua aberta?

**Comment by cleristonos** [comment]
@jonataa Acho que podemos fechar, já tem muito tempo. Podemos criar uma label para vagas perenes. 

cc: @colares
