### ISSUE TITLE
[Feira de Santana] Back-End Developer na [PAGGUE]

### ISSUE THREAD

**Issue by juniorpaggue** [devfsa/vagas#61]
## Descrição da vaga

Que tal resolver problemas e solucionar desafios como Desenvolvedor em intermediadora de pagamento e que mais cresce no Brasil? Reconhecida pelo seu foco em nicho de mercado, a Paggue busca pessoas incríveis que gostem de programar por diversão e capazes de usar os conhecimentos para elaborar soluções úteis e capazes de revolucionar o meios de pagamentos no Brasil!
Temos vagas para Pleno e Sênior!

## Local

Escritório em Feira de Santana, Getúlio Vargas, Icone Tower

## Benefícios

- Auxílio combustível / vale transporte

## Requisitos

**Obrigatórios:**
•	Experiência com ReactJS
•	Conhecimento em Laravel ou Rails
•	Proficiência em Git
•	Experiência com MySQL
•	AWS

**Desejáveis:**
•	Domínio de melhores práticas de desenvolvimento, carisma e bom relacionamento em equipe.

**Diferenciais:**
- projetos opensource

## Contratação

PJ a combinar

## Nossa empresa

A Paggue foi fundada em 2018, interior da Bahia, e hoje já somos uma das maiores intermediadoras de pagamento do nordeste.
Nossa missão é levar a melhor experiência com meio de pagamento presencial a lojistas e a determinados nichos de mercado, ajudando-as e facilitando o seu dia a dia.

## Como se candidatar

Por favor envie um email para junior@paggue.io com seu CV anexado - enviar no assunto: Vaga PAGGUE

**Comment by jonataa** [comment]
A vaga ainda está disponível?
Se não tiver, encerre a issue, por favor ;)
Obrigado!
