### ISSUE TITLE
[Feira de Santana] Deployment / Release Manager Engineer at AdMobilize

### ISSUE THREAD

**Issue by di3goleite** [devfsa/vagas#65]
## Job Description

We're looking for a very passionate engineer, with high level skills in project management, release management. If you like challenges and have a willingness to learn and share knowledge this job is for you. Those are the main responsibilities:

- Define and manage the release process of devices (we work with edge computing. We have many kind of devices across 82 countries) internally and for the in-field devices.
- Manage the testing and release plan with the team.
- Establish the release schedule based on customer feedback and optimize our delivery.
- Improve the overall quality of our device releases.
- Improve the overall communication of our device releases.
- Continuously leverage modern application development tools and frameworks and identify key strategies for cost effective release management.

## Location

Feira de Santana - Bahia

## Benefits

- Flexible Schedule
- Growing company, you'll grow with us.
- Payment set in Dollar

## Requirements

- 3-5 years of experience in a computer-science related field with project management and development experience.
- 2-4 years of experience in a production environment with hardware is a plus.
- Working with hardware releases is a plus.
- Working knowledge in Agile methodology.
- Strong leadership, communication and collaboration skills.
- Professional level English knowledge.

## Our company

We're global team of 40 determined to give everyone in the world access to building technology-driven solutions for challenges they and others face. We speak over 10 languages and we're revolutionizing the way Out-Of-Home Advertising works through of digitalizing the physical world and bringing to advertisers analytical data so they can take better decision and have the best return of investment.

## How to apply

Please send a email with you resume to careers@admobilize.com with the subject: Deployment / Release Manager

**Comment by jonataa** [comment]
A vaga ainda está disponível?
Se não tiver, encerre a issue, por favor ;)
Obrigado!

**Comment by di3goleite** [comment]
Não me recordava que essa issue ainda estava aberta. Obrigado por lembrar e me notificar. Vou encerrar aqui. 👍
