### ISSUE TITLE
[Feira de Santana] PHP Developer no Instituto Prosaber

### ISSUE THREAD

**Issue by EdcarloLima** [devfsa/vagas#7]
## Descrição da vaga

Desenvolvimento e manutenção de aplicações web com Laravel. 

## Local

Rua Georgina Erisman, 205, Feira de Santana - Centro

**Diferenciais:**

- Uma hora e meia de almoço das 12:00 às 13:30
- Jornada de segunda à sexta das 08:00 às 18:00 (Sábado hora extra)

## Requisitos

**Obrigatórios:**
- Experiência com Framework Laravel
- Experiência com Programação Orientada a Objetos - POO
- Experiência com Composer e Git
- Experiência com JavaScript

**Desejáveis:**
- Conhecimento em JavaScript Framework Vue.js

## Contratação

CLT 

## Nossa empresa

Empresa com 11 anos no ramo educacional que oferta cursos de pós-graduação online com mais de 50 mil alunos. 

## Como se candidatar

Por favor envie um email para edvania.lima@institutoprosaber.com.br com seu CV anexado - enviar no assunto: Vaga Programador PHP

**Comment by EdcarloLima** [comment]
@ssscassio por favor adiciona as labels Alocado, CLT e Laravel

**Comment by EdcarloLima** [comment]
Vaga reaberta para mais um programador php.

**Comment by jonataa** [comment]
Oi, essa vaga continua aberta?

**Comment by jonataa** [comment]
@EdcarloLima vou fechar a issue. Você poderá reabri-la caso a vaga ainda esteja disponível.
