### ISSUE TITLE
[Alocado] Front-End Developer na GOLFARMA

### ISSUE THREAD

**Issue by grmiranda** [devfsa/vagas#72]
#### Quem somos:
Somos GOLFARMA, há 13 anos no mercado e mais de 3.000 clientes em toda Bahia, somos referencia no mercado de distribuição de medicamentos.

#### Descrição da ocupação:
O profissional vai trabalhar no desenvolvimento da plataforma da empresa (Web e Mobile),  atuando em sua maior parte no desenvolvimento do Front-end com Vue.js

#### Competências desejáveis:
 ✅ Conhecimento prévio em HTML, CSS e JS
 ✅ Conhecimento prévio em Vue.js
 ✅ Proatividade e muita vontade de aprender!

#### Diferenciais!!!!!!
 ✅ Conhecimento em Vuex
 ✅ Conhecimento em Vue Router
 ✅ Conhecimento em Quasar (Framework para apps Híbridos)

Venha fazer parte de um time empenhado em entregar sempre a melhor solução, usando o que ha de melhor em tecnologia e sempre de braços abertos para novos desafios!!!! 🚀🚀

Mande uma mensagem de apresentação e seu currículo com assunto [Vaga - Front-end] para:
gabriel.dev@golfarma.com.br

**Comment by davinascimentodesouza7** [comment]
Opa, essa vaga ainda está aberta?

**Comment by jonataa** [comment]
@grmiranda pelo tempo de resposta, acredito que não esteja mais disponível. Vou encerrar a issue e caso precise reabra por favor.
