### ISSUE TITLE
[Feira de Santana] Back-End Developer na [Hostoo.io]

### ISSUE THREAD

**Issue by Hostoo-io** [devfsa/vagas#79]
## Descrição da vaga

O que acha de participar da Hostoo.io? Uma startup com melhor serviço de hospedagem cloud para sites do Brasil. 

- Perfil proativo e analítico 
- Empenhados em deixar um legado para a comunidade.
- Comportamento empreendedor.
- Temos vagas para: Estagiário, Junior, Pleno e Sênior!

## Local

Escritório, Feira de Santana - Capuchinhos/Ponto Central

## Benefícios

- Vale transporte / Auxílio combustível
- Horário flexível
- Assinatura Netflix
- Assinatura Spotify

## Requisitos

**Desejáveis:** (não é obrigatório todos os itens)

- Experiência com desenvolvimento WordPress/PHP.
- Análise e otimização de performance em sites Wordpress.
- Análise e otimização de bancos MySQL.
- Análise e identificação de problemas com envio/recebimento de e-mails em PHP.
- Migração de sites Wordpress entre servidores.
- Conhecimento em configuração de DNS.
- Experiência com cpanel, emails, mysql/phpmyadmin, postgreesql, Apache.

**Diferenciais:** (não é obrigatório)

- Inglês avançado

## Contratação

- CLT / PJ a combinar.

## Nossa empresa

**Hostoo.io** está procurando por pessoas interessadas em transformar o mercado de hospedagem de sites no mundo.

Oferecemos hospedagem cloud para sites e aplicações php através de painel próprio e inovador com automações exclusivas que reduz para **menos de 2 min o tempo de criação de uma hospedagem.** 

A startup já conta com mais de **2500 clientes em 12 meses de operação**. Para seguirmos com a expansão internacional, precisamos de pessoas focadas em resolver desafios e mostrar ao mundo a criatividade e competência dos brasileiros quando o assunto é hospedagem cloud.

## Como se candidatar

Por favor envie um email para contratacoes@hostoo.io com seu CV anexado - enviar no assunto: Vaga Back-End Developer 

Não se encaixa, mas conhece alguém que sim? Menciona a pessoa nos comentários. Boa sorte!

**Comment by jonataa** [comment]
A vaga ainda está disponível?
Se não tiver, encerre a issue, por favor ;)
Obrigado!
