### ISSUE TITLE
[Feira de Santana] Java Developer na Kamikan

### ISSUE THREAD

**Issue by ichpena** [devfsa/vagas#8]
## Descrição da vaga

Desenvolvimento de aplicações web com Java

## Local

Feira de Santana - Centro 

## Benefícios

- Auxílio Transporte
- VR de R$ 15/dia

## Requisitos

**Obrigatórios:**
- Java
- MySQL

**Desejáveis:**
- PHP
- JavaScript
- HTML5
- PHP

**Diferenciais:**
- JasperReports
- SmartGWT

## Contratação

CLT

## Nossa empresa

6 anos de experiência em sistemas clínicos, atendendo os maiores grupos de clínicas, laboratórios e hospitais de Feira de Santana e região.

## Como se candidatar

Por favor envie um email para selecao@kamikan.com.br com seu CV anexado - enviar no assunto: Vaga Desenvolvedor(a)

**Comment by jonataa** [comment]
Oi, essa vaga ainda está disponível?

**Comment by jonataa** [comment]
@ichpena vou fechar a issue. Você poderá reabri-la caso a vaga ainda esteja disponível.
