### ISSUE TITLE
Desenvolvedor C#

### ISSUE THREAD

**Issue by IELFEIRA** [devfsa/vagas#94]
## Descrição da vaga

Atividades - Desenvolvimento de Softwares WEB e Mobile
Carga horária - 44h semanais / segunda à sexta

## Local

Empresa situada no Centro de Feira de Santana

## Benefícios

- A partir de R$ 2.000,00 + Benefícios

## Requisitos

**Com conhecimentos em:**
•	DotNet Core
•	Noções de Orientação a Objetos
•	ORM
•	Banco de Dados Relacional
•	Normatização de Banco
•	Padrões de Projeto
•	Javascript
•	HTML

**Desejável conhecimento em:**
•	Nível Superior na área de TI
•	DotNet Core 2.2
•	Entity Framework Core
•	Azure Devops
•	Kubernetes
•	Arquitetura de Microsserviços

## Inscreva-se

Interessados(as) devem enviar os currículos para o e-mail ielselecaofeira@fieb.org.br , e colocar no assunto "Vaga Desenvolvedor C#"

**Comment by jonataa** [comment]
A vaga ainda está disponível?
Se não tiver, encerre a issue, por favor ;)
Obrigado!
